[pytest]

testpaths = testcases/api_tset/test__get_user_info.py
markers =
    single: single api test page
    multiple: multiple api test page
    negative: abnormal test case

;xfail_strict = True

log_cli = False

addopts = --alluredir ./report