[pytest]

testpaths = 
        testcases/api_test/test_03_login.py
        ; testcases/scenario_test/test_02_register_login_update.py
markers =
    single: single api test page
    multiple: multiple api test page
    negative: abnormal test case

;xfail_strict = True

log_cli = False

addopts = --alluredir ./allure-results