[pytest]

testpaths = testcases/api_test/test_01_get_user_info.py
markers =
    single: single api test page
    multiple: multiple api test page
    negative: abnormal test case

;xfail_strict = True

log_cli = False

addopts = --alluredir ./allure-results